# Generated by Django 3.2.4 on 2022-10-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudents',
            name='due_amount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.addcourses')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.addstudents')),
            ],
        ),
    ]
